# Generated by Django 4.0.4 on 2022-06-26 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_yourname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('introduction', models.CharField(blank=True, max_length=255, verbose_name='自己紹介')),
                ('hobby', models.CharField(blank=True, max_length=255, verbose_name='趣味')),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='yourname',
        ),
    ]
