# Generated by Django 4.0.3 on 2022-06-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uesr',
            new_name='user',
        ),
    ]
