# Generated by Django 4.0.4 on 2022-09-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("tweet", "user"), name="tweet_and_user_unique"
            ),
        ),
    ]
